[book]
authors = ["r3ntru3w4n9"]
language = "en"
multilingual = true
src = "src"
title = "Learning Machine"
description = "To do machine learning, one must learn machine."

[output.html]
mathjax-support = true
site-url = "/learning-machine/en/"
git-repository-url = "https://github.com/r3ntru3w4n9/learning-machine/tree/master/en"
git-repository-icon = "fa-github"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
