[tool.poetry]
name = "learning-machine"
version = "1.0.0"
description = "Machine learning based on answers."
authors = ["RenChu Wang <patrick1031wang@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.9"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
ipython = "^8.0.1"
ipykernel = "^6.7.0"
jupyter = "^1.0.0"
jupyter-book = "^0.12.1"
jupyter-contrib-nbextensions = "^0.5.1"
matplotlib = "^3.5.1"
numpy = "^1.22.1"
scipy = "^1.7.3"
torch = "^1.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
