[tool.poetry]
name = "learning-machine"
version = "0.1.0"
description = "Machine learning based on answers."
authors = ["RenChu Wang <patrick1031wang@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "learning_machine"}]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
jupyter-book = "^0.13.1"
matplotlib = "^3.6.2"
numpy = "^1.23.5"
scipy = "^1.9.3"
torch = "^1.13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
