[book]
authors = ["r3ntru3w4n9"]
language = "zh"
multilingual = true
src = "src"
title = "學習機器"
description = "要做機器學習，必先學習機器"

[output.html]
mathjax-support = true
site-url = "/learning-machine/zh/"
git-repository-url = "https://github.com/r3ntru3w4n9/learning-machine/tree/master/zh"
git-repository-icon = "fa-github"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
