name: Build Pages
on: [push]
jobs:
  build-and-deploy:
    name: 📃 Website Build
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 🏗️ python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: ⬇️ Python Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4
          installer-parallel: true

      - name: ⬇️ Python Dependencies
        run: poetry install --no-root

      - name: 🚧 Jupyter build
        run: poetry run jupyter book build book

      - name: 📰 Publish docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./book/_build/html
          git-config-name: "github-actions[bot]"
          git-config-email: "github-actions[bot]@users.noreply.github.com"
          commit-message: 🎉 Book deployed
