name: Website Build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Checkout
        uses: actions/checkout@v3

      - name: 🏗️ python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: ⬇️ Python Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5

      - name: ⬇️ Python Dependencies
        run: poetry install

      - name: 🇺🇸 Build English version of the book
        run: poetry run jupyter-book build book

      - name: 🇺🇸 Deploy English book
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./book/_build/html
          git-config-name: "github-actions[bot]"
          git-config-email: "github-actions[bot]@users.noreply.github.com"
          commit-message: 🎉 Book deployed
