name: PDF Build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Checkout
        uses: actions/checkout@v2

      - name: 🏗️ Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: 🇺🇸 Build English version of the book
        run: mdbook build

      - name: 🇺🇸 Deploy English book
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./book
          git-config-name: "github-actions[bot]"
          git-config-email: "github-actions[bot]@users.noreply.github.com"
          commit-message: 🎉 Book deployed
